name: composite testing
on:
  issues:
    types: [opened]

jobs:
  triage1:
    uses: xavierchanth/actions-playground/.github/workflows/issue.yaml@trunk
  triage2:
    if: never() # this allows you to test independently
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.composite/issue
