name: Issue Composite Action

on:
  workflow_call:
    secrets:
      MY_GITHUB_TOKEN:
        required: true

jobs:
  triage:
    runs-on: ubuntu-latest
    steps:
      - name: 'Move issue to "Triage"'
        uses: leonsteinhaeuser/project-beta-automations@v2.0.1
        with:
          gh_token: ${{ secrets.MY_GITHUB_TOKEN }}
          organization: xavierchanth
          project_id: 4
          resource_node_id: ${{ github.event.issue.node_id }}
