name: Windows Bash experiment

on:
  workflow_dispatch:

jobs:
  main:
    runs-on: windows-latest
    steps:
      - shell: bash
        run: |
          echo "hello"
          echo "abc123" | sed -e 's/b/d/' | cat
      - uses: actions/checkout@v4
      - shell: bash
        run: |
          ./windows-bash.sh
          # Testing env indicators
          uname
          uname -a
          uname -m
          cat /etc/os-release
